# MySQL.  Versions 4.1 and 5.0 are recommended.
# 
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: butter_development
  pool: 5
  username: butter
  password: butter
  socket: /tmp/mysql.sock

db_butter:
  adapter:   mysql2
  encoding:  utf8
  host:      192.168.170.26
  database:  butter_development
  username:  butter
  password:  butter
  reconnect: false
  pool:      5
  socket:    /tmp/mysql.sock

db_logging:
  adapter:   mysql2
  encoding:  utf8
  host:      192.168.170.26
  database:  logging
  username:  logging
  password:  logging
  reconnect: false
  pool:      5
  socket:    /tmp/mysql.sock

db_gbh:
  adapter:   mysql2
  encoding:  utf8
  host:      192.168.170.26
  database:  gbh
  username:  gbh
  password:  gbh
  reconnect: false
  pool:      5
  socket:    /tmp/mysql.sock

db_guvera:
  adapter:   mysql2
  encoding:  utf8
  host:      192.168.170.26
  database:  guvera
  username:  guvera
  password:  guvera
  reconnect: false
  pool:      5
  socket:    /tmp/mysql.sock

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: Butter_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: Butter_production
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
