#!/usr/bin/env ruby

require 'csv'
require 'date'
require 'active_record'
require 'digest/md5'

cwd = Dir.pwd
if File.basename(cwd) == 'Butter'
  require './app/models/cdn_http.rb'
  ActiveRecord::Base.establish_connection(
      :adapter    => 'mysql2',
      :encoding   => 'utf8',
      :host       => 'localhost',
      :database   => 'butter_development',
      :username   => 'butter',
      :password   => 'butter'
  )
else
  p "Must be run in rails root folder"
end

# Record layout:
# 69.28.160.164
# -
# -
# [03/Oct/2012:10:10:08 +0000] << note embedded space!
# "GET http://guvera.dl.llnw.net/artwork/UMI/Audio/457/0602527992457/0602527992457_web.jpg HTTP/1.1"
# 200
# 55207
# "https://www.guvera.com/featured"
# "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)"


http_path = File.expand_path('../Butter_data/cdn/guvera-live.logs.llnw.net/http-rerun')
Dir.entries(http_path).each do |file_name|
  full_path = "#{http_path}/#{file_name}"
  next unless File.file?(full_path)
  CSV.foreach(full_path, :col_sep => ' ') do |row|
    #p row
    cdn_http = CdnHttp.new
    cdn_http.ip_address   = row[0]
    cdn_http.happened_at  = DateTime.strptime("#{row[3]} #{row[4]}", "[%d/%b/%Y:%H:%M:%S %Z]")
    cdn_http.full_path    = row[5]
    cdn_http.status       = row[6]
    cdn_http.size         = row[7]
    cdn_http.referrer     = row[8]
    cdn_http.user_agent   = row[9]
    parts = row[5].split
    cdn_http.verb         = parts[0]
    cdn_http.path         = parts[1]
    cdn_http.http_version = parts[2]

    md5_value          = "#{cdn_http.happened_at} #{cdn_http.ip_address} #{cdn_http.status} #{cdn_http.path}"
    md5_id             = Digest::MD5.hexdigest(md5_value)
    cdn_http.md5_id    = md5_id
    printf("%s %s\n", cdn_http.md5_id, md5_value)
    existing_row = CdnHttp.where(:md5_id => md5_id).count

    cdn_http.save if existing_row == 0
  end
end




