#!/usr/bin/env ruby

require 'csv'
require 'date'
require 'active_record'

cwd = Dir.pwd
if File.basename(cwd) == 'Butter'
  require './app/models/cdn_fcs.rb'
  ActiveRecord::Base.establish_connection(
      :adapter    => 'mysql2',
      :encoding   => 'utf8',
      :host       => 'localhost',
      :database   => 'butter_development',
      :username   => 'butter',
      :password   => 'butter'
  )
else
  p "Must be run in rails root folder"
end

fcs_path = File.expand_path('../Butter_data/fcs')
["#{fcs_path}/201209.log", "#{fcs_path}/201210.log"].each do |full_path|
  next unless File.file?(full_path)
  CSV.foreach(full_path, :col_sep => "\t") do |row|
    next if row[5] =~ /^test_unsec/
    #p row
    cdn_fcs = CdnFcs.new
    cdn_fcs.mode        = row[0]
    happened_at         = "#{row[2]} #{row[3]} #{row[4]}"
    #p happened_at
    cdn_fcs.happened_at = DateTime.parse(happened_at)
    #cdn_fcs.happened_at = DateTime.strptime("#{row[3]} #{row[4]} #{row[5]}", "%Y-%m-%d %H:%M:%S %Z")
    cdn_fcs.path        = row[5]
    status              = row[15].to_i
    status              = 0 if status == '-'
    cdn_fcs.http_status = status
    cdn_fcs.ip_address  = row[16]
    existing_row = CdnFcs.where(
        :happened_at  => cdn_fcs.happened_at,
        :ip_address   => row[16],
        :path         => row[5],
        :http_status  => status
    ).count
    p cdn_fcs
    if existing_row == 0
      cdn_fcs.save
    end
  end
end
